#!/bin/ash
set -e

readonly PID_FILE="/run/teamspeak3/teamspeak3.pid"

[[ -e "$PID_FILE" ]] && rm -v "$PID_FILE"

if [[ ! -e "$APP_CONF_FILE" ]]; then
  cat >"$APP_CONF_FILE" <<EOF
machine_id=
default_voice_port=9987
voice_ip=
licensepath=
filetransfer_port=30033
filetransfer_ip=
query_port=10011
query_ip=0.0.0.0, ::
query_ip_allowlist=query_ip_allowlist.txt|query_ip_whitelist.txt
query_ip_denylist=query_ip_denylist.txt|query_ip_blacklist.txt
dbplugin=ts3db_sqlite3
dbpluginparameter=
dbsqlpath=/opt/ts3server/sql/
dbsqlcreatepath=create_sqlite
dbconnections=10
logpath=logs
logquerycommands=0
dbclientkeepdays=30
logappend=0
query_skipbruteforcecheck=0
query_buffer_mb=20
http_proxy=
license_accepted=0
serverquerydocs_path=/opt/ts3server/serverquerydocs/
query_ssh_ip=0.0.0.0, ::
query_ssh_port=10022
query_protocols=raw,http,ssh
query_ssh_rsa_host_key=ssh_host_rsa_key
query_timeout=300
query_http_ip=0.0.0.0, ::
query_http_port=10080
query_https_ip=0.0.0.0, ::
query_https_port=10443
query_pool_size=2
mmdbpath=
logquerytiminginterval=0
EOF
fi

cd "$APP_HOME"
exec /opt/ts3server/ts3server \
  "daemon=0" \
  "pid_file=$PID_FILE" \
  $APP_ADDITIONAL_PARAMS \
  "inifile=$APP_CONF_FILE"

# vim: set ft=bash ts=2 sts=2 expandtab:

